import { StyleSheet } from "react-native";

export const padding = StyleSheet.create({
  px_0: { paddingHorizontal: 0 },
  px_1: { paddingHorizontal: 4 },
  px_2: { paddingHorizontal: 8 },
  px_3: { paddingHorizontal: 12 },
  px_4: { paddingHorizontal: 16 },
  px_5: { paddingHorizontal: 20 },
  px_6: { paddingHorizontal: 24 },
  px_7: { paddingHorizontal: 28 },
  px_8: { paddingHorizontal: 32 },
  px_9: { paddingHorizontal: 36 },
  px_10: { paddingHorizontal: 40 },

  py_0: { paddingVertical: 0 },
  py_1: { paddingVertical: 4 },
  py_2: { paddingVertical: 8 },
  py_3: { paddingVertical: 12 },
  py_4: { paddingVertical: 16 },
  py_5: { paddingVertical: 20 },
  py_6: { paddingVertical: 24 },
  py_7: { paddingVertical: 28 },
  py_8: { paddingVertical: 32 },
  py_9: { paddingVertical: 36 },
  py_10: { paddingVertical: 40 },

  p_0: { padding: 0 },
  p_1: { padding: 4 },
  p_2: { padding: 8 },
  p_3: { padding: 12 },
  p_4: { padding: 16 },
  p_5: { padding: 20 },
  p_6: { padding: 24 },
  p_7: { padding: 28 },
  p_8: { padding: 32 },
  p_9: { padding: 36 },
  p_10: { padding: 40 },
});
